name: python_github_tutorial
channels:
  - conda-forge
dependencies:
  - python=3.12.*
  - numpy
  - pytest
  - pytest-cov 
  - coverage 
  - mock
  - ipython
  - nbconvert
  - jupyter
  - pygments
  - numpydoc
  - sphinx
  - nbsphinx
  - pip
  - pip:
    - sphinxcontrib-packages
    - sphinxcontrib-svg2pdfconverter
    - sphinxcontrib-video
    - sphinxcontrib-serializinghtml
