name: python_github_tutorial
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - pytest
  - pip
  - mock
  - ipython
  - nbconvert
  - jupyter
  - pygments
  - numpydoc
  - sphinx
  - sphinx_rtd_theme
  - nbsphinx
  - sphinxcontrib
  - pip:
    - sphinxcontrib-svg2pdfconverter
    - sphinxcontrib-video
    - sphinxcontrib-serializinghtml
